### ISSUE TITLE
It doesn't work in Microsoft Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by xucongli1989** [m-tmatma/CopyWithLineNumbers#1]
as title,it does not work in vs enterprise 2017 and I can't see button when I click with right mouse in editor ,but it's fine in vs enterprise 2015.thanks for your plugin.It's very good.

![1](https://user-images.githubusercontent.com/9961428/27324103-a0c087fc-55d6-11e7-8569-a82e7504900e.jpg)

![2](https://user-images.githubusercontent.com/9961428/27324179-e6e1d0e2-55d6-11e7-9e53-4fb45c79cdf4.jpg)

**Comment by m-tmatma** [comment]
@xucongli1989

I'll take time on this weekend.

**Comment by xucongli1989** [comment]
ok,thank you very much.

**Comment by m-tmatma** [comment]
I installed Visual Studio Enterprise 2017. But I couldn't reproduce it.
Did you select the partion of the code? If you don't select anything in the code editor, the menu item will not show up.

![visual-studio-2017-ent](https://user-images.githubusercontent.com/5567450/27504142-02f4840a-58c0-11e7-813a-3c169d234305.png)
![visual-studio-2017-list](https://user-images.githubusercontent.com/5567450/27504141-02f446a2-58c0-11e7-974e-040fa3718f06.png)
![visualstudio2017-menu](https://user-images.githubusercontent.com/5567450/27504143-02f6afa0-58c0-11e7-8756-605768890e81.png)

**Comment by xucongli1989** [comment]
OK,I see it ,and it must to selected some code.Sorry,I think it will copy my cursor's line number without selected code.Sorry,I give a trouble to you.Have a good time.Your pulgin is very good.
