### ISSUE TITLE
release 1.3

### ISSUE THREAD

**Issue by m-tmatma** [m-tmatma/CopyWithLineNumbers#16]
release 1.3

1. bump version to 1.3
2. update manual page
3. update README.md
4. tag 1.3
5. update https://marketplace.visualstudio.com/items?itemName=tmatma.CopyWithLineNumbers-18783
6. upload to https://github.com/m-tmatma/CopyWithLineNumbers/releases

**Comment by m-tmatma** [comment]
Hi @xucongli1989

I released version 1.3 

- https://marketplace.visualstudio.com/items?itemName=tmatma.CopyWithLineNumbers-18783
- https://github.com/m-tmatma/CopyWithLineNumbers/releases/tag/1.3

**Comment by xucongli1989** [comment]
OK,thank you.
