### ISSUE TITLE
Create Manual Page

### ISSUE THREAD

**Issue by m-tmatma** [m-tmatma/CopyWithLineNumbers#6]
Create Manual Page

**Comment by m-tmatma** [comment]
created a page at https://m-tmatma.github.io/VC/CopyWithLineNumbersManualEN.html

**Comment by m-tmatma** [comment]
Hi @xucongli1989

I wrote a manual page at https://m-tmatma.github.io/VC/CopyWithLineNumbersManualEN.html

**Comment by xucongli1989** [comment]
Very good.

**Comment by m-tmatma** [comment]
Thank you for review.
