### ISSUE TITLE
release ver 1.002

### ISSUE THREAD

**Issue by m-tmatma** [m-tmatma/CopyWithLineNumbers#8]
release ver 1.002

To releae the next version, the following are required.

- #5 is closed
- #7 is closed
- update  README.md
- update https://marketplace.visualstudio.com/items?itemName=tmatma.CopyWithLineNumbers-18783
- tag 1.002
- upload to https://github.com/m-tmatma/CopyWithLineNumbers/releases

**Comment by m-tmatma** [comment]
Hi @xucongli1989

I released version 1.2 at https://marketplace.visualstudio.com/items?itemName=tmatma.CopyWithLineNumbers-18783

**Comment by xucongli1989** [comment]
I have upgrade it,and try it again.It's very good.Thanks for your release.And I suggestion the release version should be even between `GitHub(1.002)` and `MS Market(1.2)`.Thanks a lot.

**Comment by m-tmatma** [comment]
OK
